kind: pipeline
name: default

# build step
steps:
  - name: build
    image: plugins/docker
    settings:
      repo: savchenkoroman/go-api
      tags:  [ "${DRONE_COMMIT_SHA:0:8}","latest" ]
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    environment:
      VERSION: ${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
