kind: pipeline
name: default

steps:
- name: build
  image: docker:dind
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - export VERSION="${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
    - docker build -t sav4enk0r0man/go-api:"${VERSION}" .

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
