---
apiVersion: v1
kind: Service
metadata:
  name: "go-api-svc"
  namespace: "default"
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  selector:
    app: "go-api"
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: "go-api"
 labels:
   app: "go-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "go-api"
  template:
    metadata:
      labels:
        app: "go-api"
    spec:
      containers:
        - name: go-api
          image: savchenkoroman/go-api:latest
